### PR TITLE
Github/Office365 multi-select filters fix to get suggested values

### LINKED ISSUE #3779: Github/Office365 multi-select filters fail to get suggested values
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3   | 7.16.1     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
Custom multi-select filters throw an exception when it makes a suggested value request and no values are shown.

**Preconditions**
1. Have sample data or any other information in the module

**Steps to reproduce**
1. Navigate to Github -> Panel
2. Click on a basic filter (multi select)
3. In network devtools you will see a 500 error

**Expected Result**
1. Open the multi select with suggested values for the field

**Actual Result**
1. No values are found due to the error

**Screenshots**
image

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

### PR DESCRIPTION
**Pull request by asteriscos**
Hi team,

this PR fixes multi-select filters failing to get suggested values due to the index pattern not having **attribute.fields** property.

Closes #3779 

To test it: 

- Go to Github and/or Office365 module
- See each multi-select filter suggest values and apply selected filters

Peek 2022-01-05 18-56

### CODE REVIEW

**Comment by Desvelao** [comment]
**nitpick**: The PR should be integrated with apps for Kibana 7.10.2 until 7.16.x, so we should change the base branch of PR to point to the development branch for the app of Kibana 7.10.2.

File: public/components/common/hooks/use-value-suggestion.ts [hunk 1]
```diff
@@ -69,7 +69,7 @@ export const useValueSuggestion = (
       : await data.autocomplete.getValueSuggestions({
           query,
           indexPattern: indexPattern as IIndexPattern,
-          field,
+          field: { ...field, toSpec: (options) => field },
```
Comment (Desvelao) [inline public/components/common/hooks/use-value-suggestion.ts:72]: **question**: Is this change required to work? I am not sure if only another change of this PR, solves the problem.

**Comment by Desvelao** [comment]
**review**

PR requirements:
- Add the change to the changelog

**Review by yenienserrano — APPROVED** [review]
CR: :heavy_check_mark: 
Test: :heavy_check_mark: 
LGTM
