### PR TITLE
Fixed async problem when checking for unknown fields

### LINKED ISSUE #3923: Several "The index pattern was refreshed successfully" panel appears after restarting
Wazuh | Opensearch | Rev | Security
-- | -- | -- | --
4.3.0 | 1.2.0 | 4301-1 | Wazuh Indexer

| Browser |
| ------- |
|Firefox|

**Description**

During [Windows Event](https://github.com/wazuh/wazuh/issues/12896#issuecomment-1081885456) manual testing, using OVA installation, it has been detected the following behavior:

panels

Multiple _The index pattern was refreshed successfully panels_ appear making navigability difficult.

### Steps to reproduce
- Add a new rule files -> Management > Rules > Add new rule files. 
For example:
```
<group name="windows,sysmon,">

<rule id="115001" level="10">
  <if_group>windows</if_group>
  <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1053,technique_name=Scheduled Task</field>
  <description>A Newly Scheduled Task has been Detected on $(win.system.computer)</description>
  <mitre>
    <id>T1053</id>
  </mitre>
</rule>

<rule id="115002" level="10">
  <if_group>windows</if_group>
  <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1073,technique_name=DLL Side-Loading</field>
  <description>DLL Side-Loading Detected on $(win.system.computer)</description>
  <mitre>
    <id>T1073</id>
    <id>T1574.002</id>
  </mitre>
</rule>

<rule id="115003" level="10">
  <if_group>windows</if_group>
  <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1218.010,technique_name=Regsvr32</field>
  <description>Signed Binary Proxy Execution using Regsvr32 Detected on $(win.system.computer)</description>
  <mitre>
    <id>T1218</id>
    <id>T1117</id>
  </mitre>
</rule>

<rule id="115004" level="10">
  <if_group>windows</if_group>
  <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1518.001,technique_name=Security Software Discovery</field>
  <description>Security Software Discovery Attempt has been Detected on $(win.system.computer)</description>
  <mitre>
    <id>T1518</id>
  </mitre>
</rule>

<rule id="115005" level="10">
  <if_group>windows</if_group>
  <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1548.002,technique_name=Bypass User Access Control</field>
  <description>Privilege Escalation Through Bypass of UAC has been Detected on $(win.system.computer)</description>
  <mitre>
    <id>T1548.002</id>
    <id>T1088</id>
  </mitre>
</rule>

</group>
```
- Save and restart using the interface
- Go to Modules > Security Events > Events
- Multiple panels of  _The index pattern was refreshed successfully panels_ appears

### PR DESCRIPTION
**Pull request by asteriscos**
Hi team,

this pull request solves an asynchronism issue when multiple fields are missing in the Events view rows details. Once this PR is applied **only 1 toast should pop** informing the index pattern was updated.

Closes #3923

To test it try to reproduce the linked issue.

### CODE REVIEW

File: public/components/common/modules/events.tsx [hunk 1]
```diff
@@ -190,15 +193,16 @@ export const Events = compose(
...
         });
+        if (hasUnknownFields) {
+          this.refreshKnownFields();
+        }
       }
     }
-
-    checkUnknownFields(rowDetailField) {
+  
+    async checkUnknownFields(rowDetailField) {
```
Comment (Desvelao) [inline public/components/common/modules/events.tsx:202]: **nitpick**: we need this method to be synchronous.

**Comment by Desvelao** [comment]
**thought**: I create we should change the flag to control that function is only executed one time, to a component instance variable instead of a state variable.
https://github.com/wazuh/wazuh-kibana-app/blob/fix/multiple-index-pattern-refresh-toast-3923/public/components/common/modules/events.tsx#L209-L211

Updating the state is an asynchronous method.

**suggestion**:
For example:
```ts
refreshKnownFields = async () => {
  if (!this.hasRefreshedKnownFields) {
    try {
      this.hasRefreshedKnownFields = true;
      this.isRefreshing = true;
      if (satisfyPluginPlatformVersion('<7.11')) {
        await PatternHandler.refreshIndexPattern();
      }
      this.isRefreshing = false;
      this.reloadToast();
    } catch (error) {
      this.isRefreshing = false;
      throw error;
    }
  } else if (this.isRefreshing) {
    await new Promise((r) => setTimeout(r, 150));
    await this.refreshKnownFields();
  }
};
```

> I am not sure if we need the `isRefreshing` variable in this scenario that the refresh fields of the index pattern should be done after computing if this action is required.

If we use component instance variables here, it would be interesting to apply the same change to the similar action for the Dashboard tab when there is a unknown field in some visualization.

**Review by Desvelao — APPROVED** [review]
**review**:
Code review :heavy_check_mark: 
Test: :heavy_check_mark:
