### PR TITLE
Fix stats view inaccessible for 5.x agents

### LINKED ISSUE #8149: [BUG] Fix agent stats
# Description

Currently the agent stats render a misleading error `Agent doesn't support this feature`. We need to fix this to display the agent information.

Image

Related code
[agent-stats.tsx](https://github.com/wazuh/wazuh-dashboard-plugins/blob/3abfb8150864a3d68c37cca6811eccdc279ed219/plugins/main/public/components/agents/stats/agent-stats.tsx#L139)

### PR DESCRIPTION
**Pull request by Desvelao**
### Description
This pull request fixes the agents stats view was innaccesible for 5.x agents.

Side changes:
- Fix the agent stats table were enabled when there were no results
- Adapt the agent version extraction to the new format
- Disable download CSV buttons when there is no results
 
### Issues Resolved
#8149

### Evidence
Image

Image

Disabled `Download CSV` button when there are no results:
image

### Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| With an agent 5.0.0, go to the Stats view, this should not restrict the view due to the version | :black_circle: | :black_circle: | :black_circle: |
| With an agent <4.2.0, go to the Stats view, this should restrict the view due to the version | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: With an agent 5.0.0, go to the Stats view, this should not restrict the view due to the version</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: With an agent <4.2.0, go to the Stats view, this should restrict the view due to the version</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Desvelao** [comment]
# Changes

- Adapt the agent version to the new format

File: plugins/main/public/components/agents/stats/agent-stats.tsx [hunk 1]
```diff
@@ -132,11 +134,8 @@ export const MainAgentStats = compose(
   ),
   withGuard(
     ({ agent }) => {
-      const [major, minor, patch] = agent.version
-        .replace('Wazuh v', '')
-        .split('.')
-        .map(value => parseInt(value));
-      return !(major >= 4 && minor >= 2 && patch >= 0);
+      const { raw } = getAgentVersion(agent.version);
+      return semver.lt(raw, '4.2.0');
```
Comment (Ripdiegozz) [inline plugins/main/public/components/agents/stats/agent-stats.tsx:138]: > <summary>:black_circle: With an agent 4.x, go to the Stats view, this should restrict the view due to the version</summary>

The test mentions 4.x, but should the test be restricted specifically to agents lower than 4.2.0?

Comment (Desvelao) [reply plugins/main/public/components/agents/stats/agent-stats.tsx:138]: You are right, the agents should be <4.2.0. I will change it.

**Comment by Adman23** [comment]
## :green_circle:  Tests

<details>
<summary>:green_circle:  With an agent 5.0.0, go to the Stats view, this should not restrict the view due to the version</summary>
<p>    
   Chrome: :green_circle: 
agent_5 0_chrome_stats

</p>
<p> 
    Firefox: :green_circle: 
agent_5 0_firefox_stats

</p>
</details>
<details>
<summary> :green_circle:  With an agent <4.2.0, go to the Stats view, this should restrict the view due to the version</summary>
<p>    
   Chrome: :green_circle: 

https://github.com/user-attachments/assets/3ff1673c-d48c-4ab8-bc75-f18b4d482b42

</p>
<p> 
    Firefox: :green_circle: 

https://github.com/user-attachments/assets/110100e4-fc16-4c17-8eb1-029c7f1fcfce

</p>
</details>
