### PR TITLE
Fix GitHub office365 panel information tab

### LINKED ISSUE #5164: Office365 and Github Panel information tab
| Wazuh | Opensearch | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.4.1   | 2.4.1     | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The left collapsibleNavBar in the modules Office365 and Github Panel tab doesn't work properly in Opensearch 2.4.1. When clicking the left tab with the _`i`_ icon it doesn't display the navbar with the module information.

**Preconditions**
1. Enable Github or Office365 module

**Steps to reproduce**
1. Navigate to Modules -> Github / Office365
2. Click on the `Panel` tab
3. Click on the laft tab with the _`i`_ icon

**Expected Result**
1. Display the navbra with the module configuration information

**Actual Result**
1. Nothing seems to be displayed

**Screenshots**

Peek 2023-01-25 12-45

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

### PR DESCRIPTION
**Pull request by asteriscos**
### Description

Hi team,
This PR fixes GitHub office365 panel information tab by removing the euiCollapsibleNavbar custom styles and using newer eui v34.6.0 component properties to display the close button inside the container and to remove the overlay.
 
## Important
This fix is for Opensearch 2.4.0 and above. Elasticsearch 7.10.x and 7.16.x branches don't require it.
 
### Issues Resolved
Closes #5164 

### Evidence
Peek 2023-01-25 17-00

### Test

- Navigate to Modules -> Github / Office365
- Click on the `Panel` tab
- Click on the laft tab with the _`i`_ icon
- Check it opens the drawer

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by chantal-kelm — DISMISSED** [review]
CR: ✅ 
TEST: ✅ 

Office365

https://user-images.githubusercontent.com/99441266/214621694-67ede982-f307-4139-a399-175c325f4413.mov

Github

https://user-images.githubusercontent.com/99441266/214622080-4db39790-428c-48bd-b1d9-0ed65b90cd34.mov

**Review by Tostti — APPROVED** [review]
Evidence:

https://user-images.githubusercontent.com/42900763/214641394-f002f99d-8704-41be-8868-b10a0ca9aeef.mp4

TEST:✔️
CR:✔️

LGTM

File: public/components/common/modules/panel/components/module-side-panel.tsx [hunk 1]
```diff
@@ -22,8 +22,8 @@ export const ModuleSidePanel = ({ navIsDocked = false, children, ...props }) =>
     <EuiCollapsibleNav
       isOpen={navIsOpen}
       isDocked={navIsDocked}
-      showCloseButton={true}
-      maskProps={{ headerZindexLocation: 'below', className: 'wz-no-display' }}
+      ownFocus={false}
```
Comment (Desvelao) [inline public/components/common/modules/panel/components/module-side-panel.tsx:25]: **thought**: I tested without this property definition, and add a mask under the component. It looks better visually. I checked in a previous version `4.3.10` and this doesn't have the mask, so I guess we could accept this change.

**Review by Desvelao — APPROVED** [review]
**review**

code :green_circle: 
test :green_circle: 

# Wazuh dashboard

Legend:
:black_circle:: none
:green_circle:: passed
:red_circle:: failed
:yellow_circle:: warning
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Open the info panel in the Panel tab of GitHub module | :green_circle: | :green_circle: | :black_circle: |
| Open the info panel in the Panel tab of Office365 module | :green_circle: | :green_circle: | :black_circle: |

**Details**
<details>
<summary>:green_circle: Open the info panel in the Panel tab of GitHub module</summary>

Chrome - :green_circle:

image

Firefox - :green_circle:

image

Safari - :black_circle:

</details>

<details>
<summary>:green_circle: Open the info panel in the Panel tab of Office365 module</summary>

Chrome - :green_circle:

image

Firefox - :green_circle:

image

Safari - :black_circle:

</details>
