### PR TITLE
Fix compatibility issues related to index patterns

### LINKED ISSUE #7825: Fix compatibility index pattern check
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 5.0| xyzw | Chrome, Firefox, Safari, etc |

**Description**
The dashboard has some compatibility problems with the other components and cause the index patterns can not be correctly created.

- The monitoring indices are: `wazuh-monitoring`
- The statistics indices are: `wazuh-statistics`
- The timefield of alerts data is `@timestamp` instead of `timestamp`

## Tasks
- [x] Change monitoring pattern to `wazuh-alerts*`
- [x] Change monitoring pattern to `wazuh-monitoring*`
- [x] Change monitoring pattern to `wazuh-statistics*`
- [x] Replace the check of timefield in the alerts data to `@timestatmp`
- [x] Remove the check related to `wazuh` template for the `alerts` data.
- [x] Create index patterns for the `wazuh-events` indices (wazuh-events-v5-system-activity, wazuh-events-v5-security, wazuh-events-v5-other, wazuh-events-v5-network-activity, wazuh-events-v5-cloud-services, wazuh-events-v5-applications, wazuh-events-v5-access-management, wazuh-events-v5-cloud-services-aws, wazuh-events-v5-cloud-services-azure, wazuh-events-v5-cloud-services-gcp 
- [x] Create index pattern for the `wazuh-archives` indices

**Additional context**

Related errrors:

```
Error initilizating index pattern with ID [wazuh-alerts-*]: index pattern with ID [wazuh-alerts-*] could not be created due to: time field name was not found [timestamp] in the fields. This could indicate the collection is disabled or there is a problem in the data collection or ingestion.
```

Related issues:
- https://github.com/wazuh/wazuh-indexer-plugins/issues/590
- https://github.com/wazuh/wazuh-indexer-plugins/pull/597#pullrequestreview-3369317697

### PR DESCRIPTION
**Pull request by Desvelao**
### Description

This pull request fixes some problems related to compatibility with other components:

Changes:
- Create tasks to create the index patterns:
  - `wazuh-archives*`
  - `wazuh-events-v5-system-activity*`
  - `wazuh-events-v5-security*`
  - `wazuh-events-v5-other*`
  - `wazuh-events-v5-network-activity*`
  - `wazuh-events-v5-cloud-services*`
  - `wazuh-events-v5-cloud-services-aws*`
  - `wazuh-events-v5-cloud-services-azure*`
  - `wazuh-events-v5-cloud-services-gcp*`
  - `wazuh-events-v5-applications*`
  - `wazuh-events-v5-access-management*`

- Change index pattern:
- - `wazuh-alerts*`
 - `wazuh-monitoring*`
 - `wazuh-statistics*`

- Change the time field of alerts index pattern to `@timestamp`

- Change the minimal fields of alerts index pattern to:
  - `@timestamp`
  - `agent.id`
  - `wazuh.decoders`
  - `wazuh.cluster.node`
  
- Development env:
  - Adapt the image for the manager from package
  - Add an image for the indexer from package
  - Add the indexer from package to the environement manifest as override

### Issues Resolved
#7825

### Evidence
image
image
image

### Test

> Note: the enviroment for testing requires indexer and server packages of 5.0 that can be obtained of latest execution of action builders. Then go to `docker/osd-dev/dev.yml` and comment the current `os1` service and uncoment the `os1` serivce under  `# Uncomment to run indexer from package...`. Run the enviroment with `./dev.sh <PLUGINS_ROOT_PATH> up server-local 5.0.0`

- https://github.com/wazuh/wazuh-indexer/actions/workflows/5_builderpackage_indexer.yml?query=branch%3Amain
  - https://github.com/wazuh/wazuh-indexer/actions/runs/18843648227
- https://github.com/wazuh/wazuh/actions/workflows/5_builderpackage_manager.yml
  - https://github.com/wazuh/wazuh/actions/runs/18843737420

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| With an environment with indexer and server from package, ensure all the tasks related to index patterns are green in the health check | :black_circle: | :black_circle: | :black_circle: |
| With an environment with indexer and server from package, ensure the health check task related to alerst index pattern created the index pattern with the @timestamp as time field | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: With an environment with indexer and server from package, ensure all the tasks related to index patterns are green in the health check</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: With an environment with indexer and server from package, ensure the health check task related to alerst index pattern created the index pattern with the @timestamp as time field</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by guidomodarelli** [comment]
### Test

> Note: the enviroment for testing requires indexer and server packages of 5.0 that can be obtained of latest execution of action builders. Then go to `docker/osd-dev/dev.yml` and comment the current `os1` service and uncoment the `os1` serivce under  `# Uncomment to run indexer from package...`. Run the enviroment with `./dev.sh <PLUGINS_ROOT_PATH> up server-local 5.0.0`

- https://github.com/wazuh/wazuh-indexer/actions/workflows/5_builderpackage_indexer.yml?query=branch%3Amain
  - https://github.com/wazuh/wazuh-indexer/actions/runs/18843648227
- https://github.com/wazuh/wazuh/actions/workflows/5_builderpackage_manager.yml
  - https://github.com/wazuh/wazuh/actions/runs/18843737420

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome |
| --- |  --- |
| With an environment with indexer and server from package, ensure all the tasks related to index patterns are green in the health check | 🟢
| With an environment with indexer and server from package, ensure the health check task related to alerst index pattern created the index pattern with the @timestamp as time field | 🟢

**Details**
<details>
<summary>🟢 With an environment with indexer and server from package, ensure all the tasks related to index patterns are green in the health check</summary>

Chrome - 🟢

image


</details>

<details>
<summary>🟢 With an environment with indexer and server from package, ensure the health check task related to alerst index pattern created the index pattern with the @timestamp as time field</summary>

Chrome - 🟢

image


</details>

File: docker/osd-dev/indexer/installer.sh [hunk 1]
```diff
@@ -0,0 +1,9 @@
+# Install dependencies
+apt update
+apt install -y debconf adduser procps curl
+
+# Install Wazuh server
```
Comment (guidomodarelli) [inline docker/osd-dev/indexer/installer.sh]:
```suggestion
# Install Wazuh indexer
```

File: docker/osd-dev/indexer/README.md [hunk 2]
```diff
@@ -0,0 +1,42 @@
+# Indexer
+
+This directory contains the files required to run a Wazuh indexer container using a package.
+
+## Contents
+
+- **Dockerfile**: Defines the Docker image for Wazuh Manager.
```
Comment (guidomodarelli) [inline docker/osd-dev/indexer/README.md]:
```suggestion
- **Dockerfile**: Defines the Docker image for Wazuh Indexer.
```

File: docker/osd-dev/indexer/README.md [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+- **entrypoint.sh**: Entrypoint script to initialize the container.
+- **installer.sh**: Script used to automate the installation and configuration of Wazuh Manager and its dependencies inside the container.
```
Comment (guidomodarelli) [inline docker/osd-dev/indexer/README.md]:
```suggestion
- **installer.sh**: Script used to automate the installation and configuration of Wazuh Indexer and its dependencies inside the container.
```

File: docker/osd-dev/dev.yml [hunk 4]
```diff
@@ -196,6 +196,57 @@ services:
...
+  #   entrypoint: ['bash', '/entrypoint.sh']
+  #   healthcheck:
+  #     test: [
+  #         'CMD-SHELL',
+  #         "curl -v --cacert /etc/wazuh-indexer/certs/ca.pem https://os1:9200 2>&1 | grep -q '401'",
+  #       ]
+  #     interval: 1s
+  #     timeout: 5s
+  #     retries: 120
+
```
Comment (guidomodarelli) [inline docker/osd-dev/dev.yml]: Wouldn't it be better to create another service called `os1.local`? The same as what you did with `wazuh.manager`. Then you wouldn’t need to uncomment it. And you’d have to modify the `dev.sh` script. Wouldn’t that be better?

File: plugins/main/server/plugin.ts [hunk 5]
```diff
@@ -173,10 +198,9 @@ export class WazuhPlugin implements Plugin<WazuhPluginSetup, WazuhPluginStart> {
         services: plugins.wazuhCore,
         taskName: HEALTH_CHECK_TASK_INDEX_PATTERN_ALERTS,
         options: {
-          savedObjectOverwrite: defineTimeFieldNameIfExist('timestamp'),
-          hasTemplate: true,
+          savedObjectOverwrite: defineTimeFieldNameIfExist(FIELD_TIMESTAMP),
           hasFields: INDEX_PATTERN_ALERTS_REQUIRED_FIELDS,
-          hasTimeFieldName: true,
+          hasTimeFieldName: FIELD_TIMESTAMP,
```
Comment (guidomodarelli) [inline plugins/main/server/plugin.ts]: `FIELD_TIMESTAMP` is a string, and `hasTimeFieldName` expects a boolean?

File: plugins/main/server/plugin.ts [hunk 6]
```diff
@@ -408,6 +432,138 @@ export class WazuhPlugin implements Plugin<WazuhPluginSetup, WazuhPluginStart> {
...
     );
 
+    core.healthCheck.register(
+      initializationTaskCreatorIndexPattern({
+        services: plugins.wazuhCore,
+        taskName: HEALTH_CHECK_TASK_INDEX_PATTERN_EVENTS_SYSTEM_ACTIVITY,
+        indexPatternID: WAZUH_EVENTS_SYSTEM_ACTIVITY_PATTERN,
+        options: {
+          savedObjectOverwrite: defineTimeFieldNameIfExist(FIELD_TIMESTAMP),
+          hasTimeFieldName: FIELD_TIMESTAMP,
```
Comment (guidomodarelli) [inline plugins/main/server/plugin.ts]: `FIELD_TIMESTAMP` is a string, and `hasTimeFieldName` expects a boolean?

File: plugins/main/server/plugin.ts [hunk 7]
```diff
@@ -408,6 +432,138 @@ export class WazuhPlugin implements Plugin<WazuhPluginSetup, WazuhPluginStart> {
...
+    );
+
+    core.healthCheck.register(
+      initializationTaskCreatorIndexPattern({
+        services: plugins.wazuhCore,
+        taskName: HEALTH_CHECK_TASK_INDEX_PATTERN_EVENTS_SECURITY,
+        indexPatternID: WAZUH_EVENTS_SECURITY_PATTERN,
+        options: {
+          savedObjectOverwrite: defineTimeFieldNameIfExist(FIELD_TIMESTAMP),
+          hasTimeFieldName: FIELD_TIMESTAMP,
```
Comment (guidomodarelli) [inline plugins/main/server/plugin.ts]: `FIELD_TIMESTAMP` is a string, and `hasTimeFieldName` expects a boolean?

File: plugins/main/server/plugin.ts [hunk 8]
```diff
@@ -408,6 +432,138 @@ export class WazuhPlugin implements Plugin<WazuhPluginSetup, WazuhPluginStart> {
...
+    );
+
+    core.healthCheck.register(
+      initializationTaskCreatorIndexPattern({
+        services: plugins.wazuhCore,
+        taskName: HEALTH_CHECK_TASK_INDEX_PATTERN_EVENTS_OTHER,
+        indexPatternID: WAZUH_EVENTS_OTHER_PATTERN,
+        options: {
+          savedObjectOverwrite: defineTimeFieldNameIfExist(FIELD_TIMESTAMP),
+          hasTimeFieldName: FIELD_TIMESTAMP,
```
Comment (guidomodarelli) [inline plugins/main/server/plugin.ts]: `FIELD_TIMESTAMP` is a string, and `hasTimeFieldName` expects a boolean?

File: docker/osd-dev/indexer/README.md (hunk 2 above)
Comment (Desvelao) [reply docker/osd-dev/indexer/README.md]: Fixed here: https://github.com/wazuh/wazuh-dashboard-plugins/commit/7c38afd2c2afbb4905d191870316c55e0d598400

File: docker/osd-dev/indexer/README.md (hunk 3 above)
Comment (Desvelao) [reply docker/osd-dev/indexer/README.md]: Fixed here https://github.com/wazuh/wazuh-dashboard-plugins/commit/7c38afd2c2afbb4905d191870316c55e0d598400

File: docker/osd-dev/indexer/installer.sh (hunk 1 above)
Comment (Desvelao) [reply docker/osd-dev/indexer/installer.sh]: Fixed here: https://github.com/wazuh/wazuh-dashboard-plugins/pull/7829/commits/d7cea656e9d6af86c4c23df6bdd953304e066ad3

File: plugins/main/server/plugin.ts (hunk 5 above)
Comment (Desvelao) [reply plugins/main/server/plugin.ts]: The `hasTimeFieldName` can be `true` or a string. In a later commit, this was reverted to `true`.

File: plugins/main/server/plugin.ts (hunk 6 above)
Comment (Desvelao) [reply plugins/main/server/plugin.ts]: See https://github.com/wazuh/wazuh-dashboard-plugins/pull/7829#discussion_r2472105440

File: plugins/main/server/plugin.ts (hunk 7 above)
Comment (Desvelao) [reply plugins/main/server/plugin.ts]: See https://github.com/wazuh/wazuh-dashboard-plugins/pull/7829#discussion_r2472105440

File: plugins/main/server/plugin.ts (hunk 8 above)
Comment (Desvelao) [reply plugins/main/server/plugin.ts]: See https://github.com/wazuh/wazuh-dashboard-plugins/pull/7829#discussion_r2472105440

File: docker/osd-dev/dev.yml (hunk 4 above)
Comment (Desvelao) [reply docker/osd-dev/dev.yml]: This was migrated to override the `os1` service.

File: docs/ref/modules/healthcheck.md [hunk 9]
```diff
@@ -32,28 +32,39 @@ The checks represents the unit to check and some could do some write actions suc
...
+| `index-pattern:events-network-activity`             | Validate (create if possible) the existence of a compatible index pattern for network activity events              |
+| `index-pattern:events-other`                        | Validate (create if possible) the existence of a compatible index pattern for other events                         |
+| `index-pattern:events-security`                     | Validate (create if possible) the existence of a compatible index pattern for security events                      |
+| `index-pattern:events-system-activity`              | Validate (create if possible) the existence of a compatible index pattern for system activity events               |
+| `index-pattern:monitoring`                          | Validate (create if possible) the existence of a compatible index pattern for monitoring                           |
+| `index-pattern:statistitcs`                         | Validate (create if possible) the existence of a compatible index pattern for statistics                           |
```
Comment (asteriscos) [inline docs/ref/modules/healthcheck.md]:
```suggestion
| `index-pattern:statistics`                         | Validate (create if possible) the existence of a compatible index pattern for statistics                           |
```

**Review by guidomodarelli — APPROVED** [review]
LGTM! 🟢
