### PR TITLE
Merge last changes into cloud/4.0-7.9

### LINKED ISSUE #2712: Roles mapping tab keeps loading
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.1   | 7.9.1    | 4010|

**Description**

When accessing the **roles mapping** tab, it keeps loading and does not allow to perform any action, but create a new role mapping.

**Steps to reproduce**

1. Go to 'Security > Roles mapping
2. No action can be performed, but create a new role mapping  (which cannot be removed later).

**Screenshots**

image

image

**Additional context**

Sometimes it appears to properly work with some users, but after a while, the issue returns.

Best regards,
Mayte Ariza

### PR DESCRIPTION
**Pull request by frankeros**
Hi team, this added these changes to the cloud branch

### Added

- Show the wui_ rules belong to wazuh-wui API user [#2702](https://github.com/wazuh/wazuh-kibana-app/issues/2702)
- Modified agent registration adding groups and architecture [#2666](https://github.com/wazuh/wazuh-kibana-app/issues/2666)[#2652](https://github.com/wazuh/wazuh-kibana-app/issues/2652)

### Fixed

- Create index pattern even if there aren´t available indices [#2620](https://github.com/wazuh/wazuh-kibana-app/issues/2620)
- Top bar overlayed over expanded visualizations [#2667](https://github.com/wazuh/wazuh-kibana-app/issues/2667)
- Empty inventory data in Solaris agents [#2680](https://github.com/wazuh/wazuh-kibana-app/pull/2680)
- Wrong parameters in the dev-tools autocomplete section [#2675](https://github.com/wazuh/wazuh-kibana-app/issues/2675)
- Wrong permissions on edit CDB list [#2665](https://github.com/wazuh/wazuh-kibana-app/pull/2665)
- fix(frontend): add the metafields when refreshing the index pattern [#2681](https://github.com/wazuh/wazuh-kibana-app/pull/2681)
- Error toast is showing about Elasticsearch users for environments without security [#2713](https://github.com/wazuh/wazuh-kibana-app/issues/2713)
- Error about Handler.error in Role Mapping fixed [#2702](https://github.com/wazuh/wazuh-kibana-app/issues/2702)
- Fixed message in reserved users actions [#2702](https://github.com/wazuh/wazuh-kibana-app/issues/2702)

Closes #2712

### CODE REVIEW

File: public/react-services/wz-user-permissions.ts [hunk 1]
```diff
@@ -950,33 +952,88 @@ export class WzUserPermissions{
...
+        ? notAllowInWazuhPermissions(actionResource)
+        : Object.keys(userPermissions[actionName]).some((resource) => {
+            return resource.match(actionResourceAll.replace('*', '\\*')) !== null;
+          })
+        ? Object.keys(userPermissions[actionName]).some((resource) => {
+            if (resource.match(actionResourceAll.replace('*', '\\*'))) {
+              return notAllowInWazuhPermissions(resource);
+            }
+          })
+        : userPartialResources?.length
```
Comment (Desvelao) [inline public/react-services/wz-user-permissions.ts:1022]: The App's `tsconfig.json` doesn't transpile the optional channing. We should modify this line or adapt the `tsconfig.json`

File: public/react-services/wz-user-permissions.ts [hunk 2]
```diff
@@ -950,33 +952,88 @@ export class WzUserPermissions{
...
+        });
+      };
+
+      const notAllowInWazuhPermissions = (userResource) => {
+        if (userResource !== RESOURCE_ANY) {
+          return existInWazuhPermissions(userResource)
+            ? !isAllow(userPermissions[actionName][userResource])
+            : true;
+        } else {
+          !isAllow(userPermissions[actionName][userResource]);
```
Comment (Desvelao) [inline public/react-services/wz-user-permissions.ts:1008]: Should this line be returned?

**Review by Desvelao — APPROVED** [review]
LGTM!
