### PR TITLE
fix missing && from macOS agent deployment command

### LINKED ISSUE #2988: Missing && in macOS agent deployment command
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.0   | 7.10.0     | 4101-3 |
| 4.1.0   | 7.10.2     | 4101-3 |

**Description**
The command to download, install and configure the wazuh agent on macOS does not work because it is missing a separator between the setenv arguments and the installer commands. Currently it is:
```
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-${this.state.wazuhVersion}-1.pkg && sudo launchctl setenv ${this.optionalDeploymentVariables()}sudo installer -pkg ./wazuh-agent.pkg -target /`,
```

Where it should be:
```
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-${this.state.wazuhVersion}-1.pkg && sudo launchctl setenv ${this.optionalDeploymentVariables()} && sudo installer -pkg ./wazuh-agent.pkg -target /`,
```
**Steps to reproduce**

1. Go to Agents
2. If agents have been registered before "Deploy new agent" must be clicked on.
3. Select all options necessary to deploy a macOS agents
4. Copy and paste command into a macOS computer
5. See that the package is downloaded but never installed.

**Additional context**
This should be fixed [here](https://github.com/wazuh/wazuh-kibana-app/blob/4.1-7.10/public/controllers/agent/components/register-agent.js#L409)

It is also worth noting that the optional deployment variables will misconfigure the agent because the correct syntax for `launchctl setenv` is: `Usage: launchctl setenv <<key> <value>, ...>` (with spaces separating keys from values instead of `=`), this was wrongly documented as reported here: https://github.com/wazuh/wazuh-documentation/issues/3470 and fixed here: https://github.com/wazuh/wazuh-documentation/pull/3471 and another issue should then be created to fix it on the Kibana plugin

### PR DESCRIPTION
**Pull request by jctello**
This PR Closes #2988 where && was missing from the deployment command

### CODE REVIEW

File: public/controllers/agent/components/register-agent.js [hunk 1]
```diff
@@ -406,7 +406,7 @@ export class RegisterAgent extends Component {
       rpmText: `sudo ${this.optionalDeploymentVariables()}yum install ${this.optionalPackages()}`,
       debText: `curl -so wazuh-agent.deb ${this.optionalPackages()} && sudo ${this.optionalDeploymentVariables()}dpkg -i ./wazuh-agent.deb`,
       macosText: `curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-${this.state.wazuhVersion
-        }-1.pkg && sudo launchctl setenv ${this.optionalDeploymentVariables()}sudo installer -pkg ./wazuh-agent.pkg -target /`,
+        }-1.pkg && sudo launchctl setenv ${this.optionalDeploymentVariables()} && sudo installer -pkg ./wazuh-agent.pkg -target /`,
```
Comment (pablomarga) [inline public/controllers/agent/components/register-agent.js:409]: There are two white spaces between `&& sudo installer` and the rest.
Captura de pantalla 2021-02-22 a las 10 22 27
