### PR TITLE
Fix Flyout component in Wazuh Dashboard 2.x

### LINKED ISSUE #4597: Wrong behavior from the Flyout component in Wazuh Dashboard 2.x
## Description
A new problem has been found in every version of OpenSearch 2.x, more concretely related to the OpenSearch Dashboards. 

We use the [flyout](https://elastic.github.io/eui/#/layout/flyout) component from EUI, which closes automatically when the user clicks outside it. However, in 2.x, these components will also close automatically when clicking inside them. This is not the correct behavior, and it's probably related to OSD updating the EUI library to a newer version, breaking our customized components behavior.

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/63758389/191055783-8a658ce0-0bc4-466f-a050-f672f7a45360.mp4

</details>

We'll need to hunt and fix this bug.

### Modules

- [x] Management - Rules
- [x] Mitre Attack - Intelligence
- [x] Mitre Attack - Techniques
- [x] Agents - FIM - Inventory
- [x] All Compliance - Controls Tab - Requirements Table

### Security

- [x] Policies - Create and Edit
- [x] Roles Mapping - Create and Edit
- [x] Roles - Create and Edit
- [x] User - Create and Edit

### Management

- [x] Decoders - Detail Flyout
- [x] Ruleset - Detail Flyout and Rule Info

**Related release notes**

> OpenSearch Dashboards uses [OUI](https://github.com/opensearch-project/oui) and its alias onto EUI (https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2080)
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/release-notes/opensearch-dashboards.release-notes-2.2.0.md

> Bumps @elastic/eui to v34.6.0 and @elastic/charts to v31.1.0
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/release-notes/opensearch-dashboards.release-notes-2.0.0.md

_Originally posted by @yenienserrano in https://github.com/wazuh/wazuh-kibana-app/issues/4160#issuecomment-1251188695_

### PR DESCRIPTION
**Pull request by Machi3mfl**
### Description
Wrong behavior from the Flyout component in Wazuh Dashboard 2.x.
 
### Issues Resolved
This PR fixes the flyout behavior. The `wz-flyout` was removed and replaced by the native EuiFlyout.
Closes #4597

### Test
Navigate to the following sections and test the flyout behavior. Click and explore inner content.
Defined on [https://github.com/wazuh/wazuh-kibana-app/issues/4597#issuecomment-1265856329](https://github.com/wazuh/wazuh-kibana-app/issues/4597#issuecomment-1265856329)

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [x] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: public/components/common/flyouts/wz-flyout.tsx [hunk 1]
```diff
@@ -10,21 +10,11 @@
...
-    >
-      <EuiFlyout
-        onClose={onClose}
-        {...flyoutProps}
-      >
-        {children}
-      </EuiFlyout>
-    </EuiOutsideClickDetector>
-  </EuiOverlayMask>
+export const WzFlyout = ({ children, flyoutProps = {}, onClose }) => (
```
Comment (Desvelao) [inline public/components/common/flyouts/wz-flyout.tsx:16]: **question**: I saw you use `EuiFlyout` instead of this component. If this component is not used, maybe we could remove it or use it as a wrapper of custom `EuiFlyout`, for example, that has the `wzApp` that seems is included in all the flyouts.

File: public/components/overview/compliance-table/components/requirement-flyout/requirement-flyout.tsx [hunk 2]
```diff
@@ -234,20 +234,21 @@ export class RequirementFlyout extends Component {
...
     const { onChangeFlyout } = this.props;
+    const flyoutProps = {
+      maxWidth: '60%',
+      size: 'l',
+      className: 'flyout-no-overlap wz-inventory wzApp',
+      'aria-labelledby': 'flyoutSmallTitle',
+    }
     return (
-      <WzFlyout
+      <EuiFlyout
```
Comment (Desvelao) [inline public/components/overview/compliance-table/components/requirement-flyout/requirement-flyout.tsx:244]: **nitpick**: Semicolon is missing.

File: public/components/security/policies/create-policy.tsx [hunk 3]
```diff
@@ -406,37 +406,6 @@ export const CreatePolicyFlyout = ({ closeFlyout }) => {
...
-              fill
-            >
-              Create policy
-            </EuiButton>
-          </EuiForm>
-        </EuiFlyoutBody>
-      </WzFlyout>
-      {modal}
-    </>
+                <EuiFEuiFlyout
```
Comment (yenienserrano) [inline public/components/security/policies/create-policy.tsx:409]: I think the component would be only `EuiFlyout` and should be closed.

Comment (yenienserrano) [reply public/components/security/policies/create-policy.tsx:409]: may be missing the `{modal}`

**Review by yenienserrano — CHANGES_REQUESTED** [review]

File: public/components/security/policies/create-policy.tsx (hunk 3 above)
Comment (Machi3mfl) [reply public/components/security/policies/create-policy.tsx]: Thank you @yenienserrano. Resolved

File: public/components/common/flyouts/wz-flyout.tsx (hunk 1 above)
Comment (Machi3mfl) [reply public/components/common/flyouts/wz-flyout.tsx]: I think the better way is to remove and avoid maintaining the custom component `WzFlyout`. Also, Without the `Overlay` and the `OutsiderClickDetector`, the component doesn't add any behavior only works like the native `EuiFlyout`.

**Comment by yenienserrano** [comment]
In the test I noticed that when you are editing something and you click outside the flyout it closes the flyout, and before when you were editing something, and you clicked outside the flyout a warning modal appeared that it was going to close if you wanted to continue or not the closing.

image

**Review by Mayons95 — APPROVED** [review]
TR: :heavy_check_mark: 
Evidence:
<details>
[Screencast from 13-10-22 11:27:31.webm](https://user-images.githubusercontent.com/104914131/195625036-de78f104-93a2-4baf-889f-dc8d47ca0a81.webm)

</details>

**Review by yenienserrano — COMMENTED** [review]
Reverted changes due to a bug in Elastic EUI, added back the component to handle the flyout and added the closing functions.

**Comment by AlexRuiz7** [comment]
Back to draft due to https://github.com/wazuh/wazuh-kibana-app/issues/4597#issuecomment-1282744561

**Review by AlexRuiz7 — CHANGES_REQUESTED** [review]
The flyout closes when the user clicks an option from a selector.

Easily reproducible in the Security section

**Review by AlexRuiz7 — APPROVED** [review]
Code review: ✔️ 
Test: ✔️

**Review by Mayons95 — APPROVED** [review]
