### PR TITLE
Fixed agents evolutions card

### LINKED ISSUE #3830: The agent evolution chart is continuously in loading state
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.3 | 7.17.0 | 4.3 RC3 | Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
The evolution chart is continuously in a loading state

**Preconditions**
1. Have at least one agent connected to the manager

**Steps to reproduce**
1. Navigate to the agent page

**Expected Result**
1. The agent evolution start should be displayed

**Actual Result**
1. The agent evolution chart is continuously in loading state

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

### PR DESCRIPTION
**Pull request by Machi3mfl**
Hi Team,
This PR resolves the agent evolution card permanently loading when vis index pattern doesn't exist.

Closes #3830

### CODE REVIEW

**Comment by matiasmoreno876** [comment]
CR OK ✅

**Review by matiasmoreno876 — APPROVED** [review]
TEST OK: 
image

File: public/components/wz-kibana-vis/wz-kibana-vis.tsx [hunk 1]
```diff
@@ -0,0 +1,187 @@
...
+  };
+
+  /**
+   *
+   * @param visID
+   */
+  const getRawVisualizationById = (visID: string) => {
+    // get all visualizations definitions
+    const rawVisList = rawVisualizations.getList();
+    return rawVisList ? rawVisList.filter((item) => item && item.id === visID)[0] : null;
```
Comment (Desvelao) [inline public/components/wz-kibana-vis/wz-kibana-vis.tsx:151]: **nitpick**: Use `.find()` method instead of `.filter()`

File: public/components/wz-kibana-vis/wz-kibana-vis.tsx [hunk 2]
```diff
@@ -0,0 +1,187 @@
...
+   *
+   * @param index
+   */
+  const checkVisIndexExist = async (index: string) => {
+    let res = await GenericRequest.request(
+      'GET',
+      `/api/index_patterns/_fields_for_wildcard?pattern=${index}`,
+      {}
+    );
+    return true;
```
Comment (Desvelao) [inline public/components/wz-kibana-vis/wz-kibana-vis.tsx:141]: **nitpick**: The `res` variable is not used, we could return the property of response we need instead of a literal `true`.

File: public/components/wz-kibana-vis/wz-kibana-vis.tsx [hunk 3]
```diff
@@ -0,0 +1,187 @@
...
+        throw new Error('Index pattern is not defined in visualization');
+      }
+      // checking if module is enable in confi
+      await checkVisIndexExist(visIndexPattern);
+      // set state visualization is ok for render
+      setVisCouldBeRendered(true);
+      setIsLoading(false);
+    } catch (error) {
+      // visualization couldn't be rendered
+      //console.log(`Error validating visualization: ${error}`);
```
Comment (Desvelao) [inline public/components/wz-kibana-vis/wz-kibana-vis.tsx:124]: **nitpick**: Remove this comment.

File: public/kibana-integrations/kibana-vis.js [hunk 4]
```diff
@@ -371,6 +371,10 @@ class KibanaVis extends Component {
       const currentCompleted = Math.round((currentLoaded / totalTabVis) * 100);
       if (currentCompleted >= 100) {
         this.$rootScope.rendered = 'true';
+        if(this.visID === 'Wazuh-App-Overview-General-Agents-status'){
+          this.$rootScope.resultState = 'none';
+          this.tabVisualizations.addDeadVis();
+        }
```
Comment (Desvelao) [inline public/kibana-integrations/kibana-vis.js:377]: **thought**: Why is it required?

File: public/controllers/agent/components/agents-preview.js [hunk 5]
```diff
@@ -303,7 +296,7 @@ export const AgentsPreview = compose(
                                     title={
                                       <EuiToolTip position="top" content="View agent details">
                                         <a onClick={() => this.showLastAgent()}>
-                                          {this.lastAgent.name}
+                                          {this.lastAgent.name.substring(0,5)}
```
Comment (Desvelao) [inline public/controllers/agent/components/agents-preview.js:299]: **nitpick**: We should search for another solution when the agent name is long.

File: public/controllers/agent/components/agents-preview.js [hunk 6]
```diff
@@ -321,7 +314,7 @@ export const AgentsPreview = compose(
                                     title={
                                       <EuiToolTip position="top" content="View agent details">
                                         <a onClick={() => this.showMostActiveAgent()}>
-                                          {this.mostActiveAgent.name || '-'}
+                                          {this.mostActiveAgent.name.substring(0,5) || '-'}
```
Comment (Desvelao) [inline public/controllers/agent/components/agents-preview.js:317]: **nitpick**: We should search for another solution when the agent name is long.

File: public/kibana-integrations/kibana-vis.js (hunk 4 above)
Comment (Machi3mfl) [reply public/kibana-integrations/kibana-vis.js:377]: I don't know why. But I'd prefer don't touch the `kibana-vis` component.

**Review by yenienserrano — APPROVED** [review]
Test: :heavy_check_mark:

File: server/controllers/wazuh-elastic.ts [hunk 7]
```diff
@@ -850,6 +850,25 @@ export class WazuhElasticCtrl {
     }
   }
 
+  // Check if there are indices for Monitoring
+  async existMonitoringIndices(context: RequestHandlerContext, request: KibanaRequest, response: KibanaResponseFactory) {
+    try {
+      const config = getConfiguration();
+      console.log({config})
```
Comment (Desvelao) [inline server/controllers/wazuh-elastic.ts:857]: **nitpick**: Remove the `console.log`

**Review by Desvelao — APPROVED** [review]
**review**:
Test ✅
