### PR TITLE
Fixed install macOS agent commands

### LINKED ISSUE #5886: [Register Agent] Wrong macos installation command - 4.6.0
| Wazuh | Rev  | Browser                      |
|-------|------|------------------------------|
| 4.6.0 | alpha1 | Chrome, Firefox, Safari, etc |

**Description**

Fix the installation command line in the register new agent page.

Captura de pantalla 2023-09-12 a la(s) 11 50 03

### Steps:

1. Go to Agents section
2. Click `Deploy new agent` button
3. Select macOS operting system and complete the form
4. Check the installation and start commands

### Current solution

```bash
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.6.0-1.[intel64|arm64].pkg && echo -e "WAZUH_MANAGER='0.0.0.0'\nWAZUH_AGENT_NAME='agent-name'\n" > /tmp/wazuh_envs && sudo installer -pkg ./wazuh-agent.pkg -target /
```

### Expected

```bash
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.6.0-1.intel64.pkg && echo "WAZUH_MANAGER='0.0.0.0' && WAZUH_AGENT_NAME='agent-name'" > /tmp/wazuh_envs && sudo installer -pkg ./wazuh-agent.pkg -target /
```

### Related research/tests:

- https://github.com/wazuh/wazuh-packages/issues/2205#issuecomment-1560013292
- https://github.com/wazuh/wazuh/pull/17195#issuecomment-1560044584
- https://github.com/wazuh/wazuh-kibana-app/issues/5466#issuecomment-1559922195

### PR DESCRIPTION
**Pull request by Machi3mfl**
### Description

Fix the macOS installation command
 
Closes #5886

## Intel (intel64)

Captura de pantalla 2023-09-12 a la(s) 13 57 12

Captura de pantalla 2023-09-12 a la(s) 13 57 21

```bash
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.6.0-1.intel64.pkg && echo "WAZUH_MANAGER='0.0.0.0' && WAZUH_AGENT_NAME='agent-name'" > /tmp/wazuh_envs && sudo installer -pkg ./wazuh-agent.pkg -target /
```

### Command output 

Captura de pantalla 2023-09-12 a la(s) 13 50 56

### ossec.conf with parameters specified

Captura de pantalla 2023-09-12 a la(s) 13 50 35

## Apple silicon (arm64)

Captura de pantalla 2023-09-12 a la(s) 13 57 52

Captura de pantalla 2023-09-12 a la(s) 13 58 11

```bash
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.6.0-1.arm64.pkg && echo "WAZUH_MANAGER='0.0.0.0' && WAZUH_AGENT_NAME='agent-name'" > /tmp/wazuh_envs && sudo installer -pkg ./wazuh-agent.pkg -target /
```

### Command output 

image

### ossec.conf with parameters specified

image

### Test

1. Go to Agents section
2. Click Deploy new agent button
3. Select macOS operting system and complete the form
4. Check the installation and start commands

### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by jbiset — APPROVED** [review]
# CR: :green_circle: 

# TEST UI

## :green_circle:  Intel (intel64)

Intel64_OS_Selector

Intel64_Commands

## :green_circle:  Apple silicon (arm64)

AppleSilicon_OS_Selector

AppleSilicon_Commands

**Review by jbiset — DISMISSED** [review]

File: plugins/main/public/controllers/register-agent/services/register-agent-os-commands-services.tsx [hunk 1]
```diff
@@ -45,8 +45,13 @@ const getAllOptionalsMacos = (
   return Object.entries(paramNameOrderList).reduce(
     (acc, [key, value]) => {
       if (optionals[value]) {
-        acc += `${optionals[value]}\\n`;
+        acc += `${optionals[value]}`;
       }
+
+      if (Number.parseInt(key) + 1 < Object.entries(optionals).length) {
+        acc += ` && `;
+      }
```
Comment (Desvelao) [inline plugins/main/public/controllers/register-agent/services/register-agent-os-commands-services.tsx:53]: **nitpick**: I think this could cause bugs.

EDITED: image


**suggestion**: I understand you want to join the declaration of environment variables. I think a cleaner way to do this is using the `Array.prototype.join()` method instead.

Comment (Machi3mfl) [reply plugins/main/public/controllers/register-agent/services/register-agent-os-commands-services.tsx]: Fixed in https://github.com/wazuh/wazuh-kibana-app/pull/5888/commits/d5f3d2ca48fe0ae196d97997c769ca5ccfb6ee0d


https://github.com/wazuh/wazuh-kibana-app/assets/6089438/1d941f77-36bb-4aa2-ba7f-3ba4e5fe38a6

**Review by jbiset — APPROVED** [review]

**Review by Tostti — APPROVED** [review]
Test 

Intel :green_circle:
image

Apple silicon :green_circle:
image


TEST:✔️
CR:✔️

LGTM
