### PR TITLE
Fix errors in PDF reports

### LINKED ISSUE #3225: Bug generating a PDF in an agent config
- Bug log collection looks double when generating a pdf in the configuration of an agent

- `Who data` appears three times with different information
image

### PR DESCRIPTION
**Pull request by pablomarga**
Hi teams this PR solves: 

- Bug log collection looks double when generating a pdf in the configuration of an agent
- `Who data` appears three times with different information
- Wrong date format
- Some columns dissapeared if the names were too long.

### How to test
Go to agents > select an agent > generate PDF report. Also generating reports in other section of the app.

Closes #3225

### CODE REVIEW

**Review by Machi3mfl — APPROVED** [review]
Fixed, no more duplicated data.
Screen Shot 2021-05-19 at 17 06 09

Screen Shot 2021-05-19 at 17 06 33

File: server/lib/reporting/printer.ts [hunk 1]
```diff
@@ -490,9 +490,27 @@ export class ReportPrinter{
           style: 'standard'
         }
       })
-    });
-  
-    const widths = new Array(columns.length - 1).fill('auto');
+    }); 
+
+    // 385 el width máximo inicial por columna
```
Comment (Desvelao) [inline server/lib/reporting/printer.ts:495]: In english

File: server/lib/reporting/printer.ts [hunk 2]
```diff
@@ -490,9 +490,27 @@ export class ReportPrinter{
...
+    let totalLength = columns.length - 1;
+    const widthColumn = 385/totalLength;
+    let totalWidth = totalLength * widthColumn;
+    const widthCharacter = 5; //min width para un caracter
```
Comment (Desvelao) [inline server/lib/reporting/printer.ts:499]: In english

File: server/lib/reporting/printer.ts [hunk 3]
```diff
@@ -490,9 +490,27 @@ export class ReportPrinter{
...
+    const widths = new Array;
+    
+    for (let step = 0; step < columns.length - 1; step++) {
+      let column_length = tableRows[0][step].text.length * widthCharacter;
```
Comment (Desvelao) [inline server/lib/reporting/printer.ts:503]: The logic to calculate the column width is only considering the first line instead of all lines. This could be a cause of possible bugs.

**Review by Desvelao — CHANGES_REQUESTED** [review]
Could you use `camelCase` for the variable names instead of `snake_case`?

File: server/lib/reporting/agent-configuration.ts [hunk 4]
```diff
@@ -285,7 +285,7 @@ export const AgentConfiguration = {
           config: [
             { component: 'syscheck', configuration: 'syscheck', matrix: true }
           ],
-          tabs: ['General', 'Who data'],
+          tabs: ['General','File limit', 'Disk quota','File size','Who data','Synchronization'],
```
Comment (Desvelao) [inline server/lib/reporting/agent-configuration.ts:288]: This shouldn't be necessary

**Review by Desvelao — APPROVED** [review]
