### PR TITLE
Fix/3673 fixing double flyout clicking in a policy

### LINKED ISSUE #3673: Closing policy edit flyout opens create new policy flyout
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2   | 7.10.2 | 4xxx | Basic, ODFE, Xpack |

| Browser |
| ------- |
| Chrome, Firefox, Safari, etc|

**Description**
Short description of your issue.

**Preconditions**
1. Have existing policies

**Steps to reproduce**
1. Navigate to Security -> Policies
2. Click on a policy row to edit it
3. Click outside the flyout to close it
4. See _Create new policy_ flyout open

**Expected Result**
1. Just close the edit flyout

**Actual Result**
1. Closes edit flyout and opens new policiy flyout

**Screenshots**
Peek 2021-11-02 11-47

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

### PR DESCRIPTION
**Pull request by CPAlejandro**
In this PR we fixed that when we selected a policy from the table, instead of only opening the policy editor, we opened it and when we closed it, the Flyout was also opened to create a policy.

To test it, go to Security / Policies, click on any one and try to close it or click outside of it, the flyout should close and no other should open.

Closes #3673

### CODE REVIEW

File: public/components/security/policies/policies.tsx [hunk 1]
```diff
@@ -183,7 +183,7 @@ export const Policies = () => {
         </EuiPageContentHeaderSection>
       </EuiPageContentHeader>
       <EuiPageContentBody>
-        <PoliciesTable loading={loading} policies={policies} editPolicy={editPolicy} createPolicy={createPolicy} updatePolicies={getPolicies}></PoliciesTable>
+        <PoliciesTable loading={loading} policies={policies} editPolicy={editPolicy} updatePolicies={getPolicies}></PoliciesTable>
```
Comment (AlexRuiz7) [inline public/components/security/policies/policies.tsx:186]: These long lines could be splitted into several lines to improve readbility

```html
<PoliciesTable 
  loading={loading} 
  policies={policies} 
  editPolicy={editPolicy} 
  updatePolicies={getPolicies}>
</PoliciesTable>
```

**Review by AlexRuiz7 — APPROVED** [review]
CR: ✔️ 
Test: ✔️

**Review by asteriscos — APPROVED** [review]
Test: :heavy_check_mark: 
CR: :heavy_check_mark:
