### PR TITLE
Modified agent registration adding groups and arch

### LINKED ISSUE #2652: Agent deployment URLs don't work for some versions or architectures
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.0.1   | 7.9.1     | 4010 |

**Description**
URLs provided in the agent deployment don't fully cover the possible versions and architectures that Wazuh supports. Notably CentOS/RHEL5 use a different URL than the one provided as do all Linux architectures other than x86_64

**Steps to reproduce**

1. Go to the Agents section
2. Click on Deploy New Agent
3. Select RedHat / CentOS
4. Attempt to use on RHEL5, a 32-bit, aarch64 or armhf computer.

**Screenshots**
image

**Additional context**
For agents with CentOS/RHEL5 the valid URLs are:
- https://packages.wazuh.com/4.x/yum5/i386/wazuh-agent-4.0.1-1.el5.i386.rpm for 32 bit
- https://packages.wazuh.com/4.x/yum5/x86_64/wazuh-agent-4.0.1-1.el5.x86_64.rpm for 64 bit

The package provided for the CentOS/RHEL 6 and above would not work for the following architectures:
- [i386](https://packages.wazuh.com/4.x/yum/wazuh-agent-4.0.1-1.i386.rpm)
- [aarch64](https://packages.wazuh.com/4.x/yum/wazuh-agent-4.0.1-1.aarch64.rpm)
- [armhf](https://packages.wazuh.com/4.x/yum/wazuh-agent-4.0.1-1.armv7h.rpm)

For Debian/Ubuntu and similar:
 - [i386](https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.0.1-1_i386.deb)
 - [aarch64](https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.0.1-1_arm64.deb)
 - [armhf](https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.0.1-1_armhf.deb)

### LINKED ISSUE #2666: Add groups to the agent deployment form
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.x   | 7.x     | 400x |

**Description**
We should add the groups in the agent deployment form. We could use the deployment variable `WAZUH_AGENT_GROUP` (https://documentation.wazuh.com/4.0/installation-guide/wazuh-agent/deployment_variables/linux/deployment_variables_yum.html)

### PR DESCRIPTION
**Pull request by pablomarga**
Hi team! This PR change the form of an agent registration adding the options of selecting the architecture of your OS and enrolling the agent to a group. 
This PR close #2652 and close #2666

### CODE REVIEW

File: public/controllers/agent/components/register-agent.js [hunk 1]
```diff
@@ -151,6 +208,69 @@ export class RegisterAgent extends Component {
...
+      return result.data.data.affected_items.map(item =>
+        ({ label: item.name, id: item.name })
+      )
+    } catch (error) {
+      return [];
+    }
+  }
+
+  optionalDeploymentVariables() {
+    let deployment = `WAZUH_MANAGER='${this.state.serverAddress}' ${this.state.selectedOS == 'win' ? `WAZUH_REGISTRATION_SERVER='${this.state.serverAddress}' ` : ''}${this.state.needsPassword
```
Comment (frankeros) [inline public/controllers/agent/components/register-agent.js:227]: deployment is a `const`

File: public/controllers/agent/components/register-agent.js [hunk 2]
```diff
@@ -151,6 +208,69 @@ export class RegisterAgent extends Component {
...
+        ? " WAZUH_PROTOCOL='UDP'"
+        : ''
+      }${this.state.selectedGroup.length ? `WAZUH_AGENT_GROUP='${this.state.selectedGroup.map(item => item.label).join(',')}' ` : ''}`
+    return deployment;
+  }
+
+  optionalPackets() {
+    let ret = `https://packages.wazuh.com/4.x/yum5/x86_64/wazuh-agent-${this.state.wazuhVersion}-1.x86_64.rpm`;;
+
+    if (this.state.selectedOS == 'rpm' && this.state.selectedVersion == 'centos5' && this.state.selectedArchitecture == 'i386') {
```
Comment (frankeros) [inline public/controllers/agent/components/register-agent.js:240]: to avoid this if-else chain, you can use some specific functions to resolve related data for example
```js
switch(this.state.selectedOS) {
  case 'rpm': 
    return resolveRPMPackage();
  case 'deb': 
    return resolveDEBPackage():
  default: 
   return: `https://packages.wazuh.com/4.x/yum5/x86_64/wazuh-agent-${this.state.wazuhVersion}-1.x86_64.rpm`;
}
```
the extra functions like `resolveRMPPackage()` can be a similar switch approach 
the important is to keep functions easy to read

File: public/controllers/agent/components/register-agent.js [hunk 3]
```diff
@@ -151,6 +208,69 @@ export class RegisterAgent extends Component {
...
+      ? ` WAZUH_REGISTRATION_PASSWORD='${this.state.wazuhPassword}'`
+      : ''
+      }${this.state.udpProtocol
+        ? " WAZUH_PROTOCOL='UDP'"
+        : ''
+      }${this.state.selectedGroup.length ? `WAZUH_AGENT_GROUP='${this.state.selectedGroup.map(item => item.label).join(',')}' ` : ''}`
+    return deployment;
+  }
+
+  optionalPackets() {
```
Comment (frankeros) [inline public/controllers/agent/components/register-agent.js:237]: packages

File: public/controllers/agent/components/register-agent.js [hunk 4]
```diff
@@ -151,6 +208,69 @@ export class RegisterAgent extends Component {
...
+    let ret = `https://packages.wazuh.com/4.x/yum5/x86_64/wazuh-agent-${this.state.wazuhVersion}-1.x86_64.rpm`;;
```
Comment (frankeros) [inline public/controllers/agent/components/register-agent.js:238]: you don't need the variable, return the value instead.

**Review by frankeros — CHANGES_REQUESTED** [review]

**Review by frankeros — APPROVED** [review]
LGTM!

**Review by gabiwassan — APPROVED** [review]
LGTM

File: public/controllers/agent/components/register-agent.js [hunk 5]
```diff
@@ -34,6 +37,46 @@ import {
...
+];
+
+const versionBottonsCentos = [
+  {
+    id: 'centos5',
+    label: 'CentOS5'
+  },
+  {
+    id: 'centos6',
+    label: 'CentOS6 o superior'
```
Comment (gabiwassan) [inline public/controllers/agent/components/register-agent.js:77]: `o` is in Spanish 🤔
possible options:
```
CentOS6 or superior 
CentOS6 or higher.
```

**Review by gabiwassan — CHANGES_REQUESTED** [review]
Hi Pablo, 
I did some tests and detected an error, here are the steps to reproduce it:
1. Select Redhat / CentOS and CentOS6 or Higher.
2. Select aarch64.
3. We switch to CentOS5:

In the Copy Command of "Install and enroll the agent" it is left with the word "undefined" at the end, this is because it does not have a default architecture selection when changing the options.

image

Just some details but Great job!! 👍🏼

**Comment by Desvelao** [comment]
I was testing the PR, and found a pair of issues:
1. The step which allows you to introduce the password is not showing:
image
How to reproduce this:
Enable the `use_password` setting in the `auth` block of manager's ossec.conf. You can use the app to do this in `Management` > `Configuration` > `Edit configuration` or edit the file using the terminal with an editor. After that, you should restart the manager.
image
The input with the password should appear in the next cases:
- Use password enabled but not defined: `use_password` to `yes` (manager's ossec.conf). File in manager path `/var/ossec/etc/authd.pass` didn't create.
- Use password enabled and defined:  `use_password` to `yes` (manager's ossec.conf). File in manager path `/var/ossec/etc/authd.pass` created with a password.

You can find more info [here](https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/auth.html?highlight=use_password#use-password): 
2. There is no separation between the definition of the variable WAZUH_PASSWORD and the rest of the command
image

**Comment by Desvelao** [comment]
> Hi Pablo,
> I did some tests and detected an error, here are the steps to reproduce it:
> 
> 1. Select Redhat / CentOS and CentOS6 or Higher.
> 2. Select aarch64.
> 3. We switch to CentOS5:
> 
> In the Copy Command of "Install and enroll the agent" it is left with the word "undefined" at the end, this is because it does not have a default architecture selection when changing the options.
> 
> image
> 
> Just some details but Great job!! 👍🏼

Maybe we should sure all the options (OS, OS version, architecture) are selected to show the command? We are showing a url package when architecture is not selected for example.
image

File: public/controllers/agent/components/register-agent.js [hunk 6]
```diff
@@ -118,25 +173,27 @@ export class RegisterAgent extends Component {
...
-    if (!this.state.needsPassword || this.state.hidePasswordInput)
-      steps.splice(2, 1);
-    return steps;
+  setArchitecture(selectedArchitecture) {
+    this.setState({ selectedArchitecture });
+  }
+
+  setVersion(selectedVersion) {
+    this.setState({ selectedVersion });
+  }
```
Comment (Desvelao) [inline public/controllers/agent/components/register-agent.js:193]: Should we restart the `selectedArchitecture` variable (set to empty strin '') when a `selectedVersion` (OS version) is selected?

**Comment by Desvelao** [comment]
I tested this PR and if you don't select architecture for Debian or a version or architecture for Centos, the step to install the agent is missing and the start agent step is showing. Maybe we should show in this step some message saying some information is needed or something like that. Same for the step to start the agent.

Screenshot:
image

**Comment by Desvelao** [comment]
Changes:
- Replaced OS options buttons by a buttons group:
image

- Added a message when some OS options is missing:
image
image
image

- Hid the start agent step when there are OS options missing

- Modified some texts

File: public/controllers/agent/components/register-agent.js [hunk 7]
```diff
@@ -328,7 +336,7 @@ export class RegisterAgent extends Component {
     const groupInput = (
       <EuiText>
         <p>
-          You can predefine the group where you want to enroll the agent.
+          Select one or more existing groups
```
Comment (frankeros) [inline public/controllers/agent/components/register-agent.js:339]: current instad of existing (?)

**Review by Desvelao — APPROVED** [review]

**Review by gabiwassan — APPROVED** [review]
