### PR TITLE
Fix flyout details width

### LINKED ISSUE #7986: Fix width in Normalization flyout
# Description

Currently the flyout in the Normalization app adjusts its width based on the content width. As the content width may vary a great deal, we need to establish a fixed flyout width and make the content width constrain to the flyout. This will help improve the user experience.

## Tasks

- [ ] Make the Normalization details flyout have a fixed width.

### PR DESCRIPTION
**Pull request by Desvelao**
### Description

This pull request fixes the flyout details width in the Normalization module.

Changes:
- Fix the flyout details width
- Fix the `key` column of KVDB details
- Fix render of Normalization module using the old menu
- Replace `EuiCodeEditor` by `EuiCodeBlock` in Normalization
 
### Issues Resolved

#7986

### Evidence
- Overview
image
image

- Decoders
image
image
image

- KVDBs
image
image

### Test

Legend:
:black_circle:: none
:green_circle:: pass
:yellow_circle:: warning
:red_circle:: fail
:white_circle:: not applicable

## UI

| Test | Chrome | Firefox | Safari |
| --- |  --- | --- | --- |
| Go to Normalization and ensure the detail flyout for Overview, Decoders and KVDBs keep the same width when changing between tabs of the details. | :black_circle: | :black_circle: | :black_circle: |
| Go to Normalization > KVDBs > open details and ensure the `key` column has less than the value column. | :black_circle: | :black_circle: | :black_circle: |

**Details**
<details>
<summary>:black_circle: Go to Normalization and ensure the detail flyout for Overview, Decoders and KVDBs keep the same width when changing between tabs of the details.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

<details>
<summary>:black_circle: Go to Normalization > KVDBs > open details and ensure the `key` column has less than the value column.</summary>

Chrome - :black_circle:

Firefox - :black_circle:

Safari - :black_circle:

</details>

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

File: plugins/main/public/components/normalization/components/buttons/button-open-flyout.tsx [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+export const ButtonOpenFlyout = props => (
+  <WzButtonPermissionsOpenFlyout
+    {...props}
+    flyoutProps={{
+      style: {
+        maxWidth: '1000px',
+        width: '60%',
+      },
+    }}
+  ></WzButtonPermissionsOpenFlyout>
```
Comment (guidomodarelli) [inline plugins/main/public/components/normalization/components/buttons/button-open-flyout.tsx:13]: Why don't you directly add these styles to the component that you imported above? That way all the other components or files that use this component will already have them by default.

Comment (Desvelao) [reply plugins/main/public/components/normalization/components/buttons/button-open-flyout.tsx:13]: The `WzButtonPermissionsOpenFlyout` is generic, adding these styles could cause undesired effect. This could be discussed.

The creation of a new component that embeds these props definition avoids the requirement to define them in different components. For another hand, the `WzButtonPermissionsOpenFlyout` component is defined in `main` plugin and the **Normalization** view should be moved to the SA plugin where the access to the `WzButtonPermissionsOpenFlyout` component could not be possible. So centralizating this, the `WzButtonPermissionsOpenFlyout` component will be replaced in the SA and the width props do not require touch multiple files.

**Comment by guidomodarelli** [comment]
### 🟢 Test Legend

| Symbol                | Meaning                                                              |
| --------------------- | -------------------------------------------------------------------- |
| ⚫      | The test hasn't started yet.                                         |
| 🟢      | All checks passed.                                                   |
| 🟡     | There is at least one expected fail or skipped test and no failures. |
| 🔴        | There is at least one failed check.                                  |
| ⚪      | Doesn't apply.                                                       |
| 🔧   | Request changes.                                                     |
| ❓     | Needs more information.                                              |


# 🧪 Test 2025/12/22

CR 🟢
TEST 🟢

- Overview

image

image

- Decoders

image

image

image

- KVDBs

image

image
